from visualization_system import Visualizer, SpectrogramLayer, BeatThisLayer, BeatProbabilityLayer, DownbeatProbabilityLayer


viz = Visualizer()
viz.add_layer(SpectrogramLayer())
viz.add_layer(BeatProbabilityLayer())
viz.add_layer(DownbeatProbabilityLayer())
viz.load_all_layers(
    audio_path="PARTITURAS_MEI/ChopinNocOP27n2-Full.wav",  # audio file to be analized
    beat_probs_file="beat_probs.npz"                       # beatThis_probability generated by beat_this_call.py
)
fig, ax = viz.draw()

viz.show()
