from visualization_system import Visualizer
from Spectogram_layer import SpectrogramLayer
from BeatThis_layers import (
    BeatProbabilityLayer,
    DownbeatProbabilityLayer,
    BeatAccurateLayer
)


viz = Visualizer()
viz.add_layer(SpectrogramLayer())
viz.add_layer(BeatProbabilityLayer(color=(1, 0, 0, 0.7))) # Red with some transparency
viz.add_layer(DownbeatProbabilityLayer(color=(0, 0, 1, 0.7)))   # Blue with some transparency
viz.add_layer(BeatAccurateLayer(beat_color=(1, 1, 0, 1), downbeat_color=(0, 1, 0, 1))) # Yellow beats, Green downbeats
viz.load_all_layers(
    audio_path="PARTITURAS_MEI/ChopinNocOP27n2-Full.wav",  # audio file to be analized
    beat_probs_file="beat_probs.npz"                       # beatThis_probability generated by beat_this_call.py
)
fig, ax = viz.draw()

viz.show()