# Updated imports for new structure
from beat_spec_visual.visualization.visualizer import Visualizer
from beat_spec_visual.visualization.layers.spectrogram import SpectrogramLayer
from beat_spec_visual.visualization.layers.beat_this import (
    BeatProbabilityLayer,
    DownbeatProbabilityLayer,
    BeatAccurateLayer
)

viz = Visualizer()
viz.add_layer(SpectrogramLayer())
viz.add_layer(BeatProbabilityLayer())
viz.load_all_layers(
    audio_path="PARTITURAS_MEI/Chopin_op10_no3_p01.wav",  # audio file to be analized
    #score_file="PARTITURAS_MEI/Chopin_op10_no3_p01-mei.maps.json"
    # maps_file="PARTITURAS_MEI/Chopin_op10_no3_p01-maps.json"           
    beat_file="beat_probs.npz"                       # beatThis_probability generated by beat_this_call.py

)
fig, ax = viz.draw()
viz.TurnInToSVG("000 SPECTOGRAM.svg")